# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "WildwoodMo.com - A Wildwood Missouri Community Site."
description: > # this means to ignore newlines until "email:"
   A website dedicated to information about the City of Wildwood, Missouri.

email: wildwoodmo@christoc.com
#blog logo
logo: "/assets/images/wildwoodmo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/WildwoodSign.jpg"

name: 'Chris Hammond'
author: 'Chris Hammond'
author_image: "/assets/images/ChrisHammond_sq_200.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""MeasureMeasure
#used to display twitter cards
twitter_handle: '@christoc'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/christoc
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: "?text="
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/christopherhammond
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: "?t=""
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/wildwoodmo/
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
