#Site settings 
title: "WildwoodMo.com - A Wildwood Missouri Community Site."
description: > # this means to ignore newlines until "email:"
   An unofficial website dedicated to information about the City of Wildwood Missouri.

email: 
#blog logo
logo: "/assets/images/wildwoodmo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/WildwoodSign.jpg"

name: 'WildwoodMO.com'
author: 'WildwoodMO.com'
author_image: "/assets/images/wildwoodmo.png"
google_analytics: UA-69145-49

paginate:	5

url: https://www.wildwoodmo.com
baseurl: 
#used to display twitter cards
twitter_handle: '@Wildw00dMo'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/Wildw00dMo
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

